
package thevoz.ch;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapServer", targetNamespace = "http://notice.server.soap.common.exchange.autinform.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapServer {


    /**
     * 
     * @return
     *     returns boolean
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "success", partName = "success")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getAuthenticationRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getAuthenticationResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getAuthentication/Fault/Fault")
    })
    public boolean getAuthentication()
        throws Fault
    ;

    /**
     * 
     * @param category
     * @param status
     * @param publishDate
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForCategoryWithStatusRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForCategoryWithStatusResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForCategoryWithStatus/Fault/Fault")
    })
    public LongArray getNoticeListForCategoryWithStatus(
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "status", partName = "status")
        String status,
        @WebParam(name = "publishDate", partName = "publishDate")
        XMLGregorianCalendar publishDate)
        throws Fault
    ;

    /**
     * 
     * @param category
     * @param publishDate
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForCategoryRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForCategoryResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForCategory/Fault/Fault")
    })
    public LongArray getNoticeListForCategory(
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "publishDate", partName = "publishDate")
        XMLGregorianCalendar publishDate)
        throws Fault
    ;

    /**
     * 
     * @param publishDate
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeList/Fault/Fault")
    })
    public LongArray getNoticeList(
        @WebParam(name = "publishDate", partName = "publishDate")
        XMLGregorianCalendar publishDate)
        throws Fault
    ;

    /**
     * 
     * @param category
     * @param status
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListForCategoryWithStatusRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListForCategoryWithStatusResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListForCategoryWithStatus/Fault/Fault")
    })
    public LongArray getActualCantonNoticeListForCategoryWithStatus(
        @WebParam(name = "category", partName = "category")
        String category,
        @WebParam(name = "status", partName = "status")
        String status)
        throws Fault
    ;

    /**
     * 
     * @param category
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListForCategoryRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListForCategoryResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListForCategory/Fault/Fault")
    })
    public LongArray getActualCantonNoticeListForCategory(
        @WebParam(name = "category", partName = "category")
        String category)
        throws Fault
    ;

    /**
     * 
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeListResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getActualCantonNoticeList/Fault/Fault")
    })
    public LongArray getActualCantonNoticeList()
        throws Fault
    ;

    /**
     * 
     * @param subscriptionId
     * @param publishDate
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForSubscriberRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForSubscriberResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForSubscriber/Fault/Fault")
    })
    public LongArray getNoticeListForSubscriber(
        @WebParam(name = "publishDate", partName = "publishDate")
        XMLGregorianCalendar publishDate,
        @WebParam(name = "subscriptionId", partName = "subscriptionId")
        int subscriptionId)
        throws Fault
    ;

    /**
     * 
     * @param publishDateFrom
     * @param publishDateTo
     * @param subscriptionId
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForSubscriberDateRangeRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForSubscriberDateRangeResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeListForSubscriberDateRange/Fault/Fault")
    })
    public LongArray getNoticeListForSubscriberDateRange(
        @WebParam(name = "publishDateFrom", partName = "publishDateFrom")
        XMLGregorianCalendar publishDateFrom,
        @WebParam(name = "publishDateTo", partName = "publishDateTo")
        XMLGregorianCalendar publishDateTo,
        @WebParam(name = "subscriptionId", partName = "subscriptionId")
        int subscriptionId)
        throws Fault
    ;

    /**
     * 
     * @param publishDate
     * @return
     *     returns thevoz.ch.LongArray
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeList", partName = "noticeList")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getPublishedNoticeListRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getPublishedNoticeListResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getPublishedNoticeList/Fault/Fault")
    })
    public LongArray getPublishedNoticeList(
        @WebParam(name = "publishDate", partName = "publishDate")
        XMLGregorianCalendar publishDate)
        throws Fault
    ;

    /**
     * 
     * @param docId
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeHtml", partName = "noticeHtml")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeHtmlRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeHtmlResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeHtml/Fault/Fault")
    })
    public String getNoticeHtml(
        @WebParam(name = "docId", partName = "docId")
        long docId)
        throws Fault
    ;

    /**
     * 
     * @param docId
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeXml", partName = "noticeXml")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeXmlRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeXmlResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeXml/Fault/Fault")
    })
    public String getNoticeXml(
        @WebParam(name = "docId", partName = "docId")
        long docId)
        throws Fault
    ;

    /**
     * 
     * @param publishDate
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "noticeXmls", partName = "noticeXmls")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeXmlsRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeXmlsResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticeXmls/Fault/Fault")
    })
    public String getNoticeXmls(
        @WebParam(name = "publishDate", partName = "publishDate")
        XMLGregorianCalendar publishDate)
        throws Fault
    ;

    /**
     * 
     * @param docId
     * @return
     *     returns byte[]
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "pdf", partName = "pdf")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticePdfRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticePdfResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getNoticePdf/Fault/Fault")
    })
    public byte[] getNoticePdf(
        @WebParam(name = "docId", partName = "docId")
        long docId)
        throws Fault
    ;

    /**
     * 
     * @param docId
     * @return
     *     returns byte[]
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "file", partName = "file")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getAttachmentRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getAttachmentResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getAttachment/Fault/Fault")
    })
    public byte[] getAttachment(
        @WebParam(name = "docId", partName = "docId")
        long docId)
        throws Fault
    ;

    /**
     * 
     * @param docId
     * @return
     *     returns thevoz.ch.Provider
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "provider", partName = "provider")
    @Action(input = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getProviderFromNoticeRequest", output = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getProviderFromNoticeResponse", fault = {
        @FaultAction(className = Fault.class, value = "http://notice.server.soap.common.exchange.autinform.de/SoapServer/getProviderFromNotice/Fault/Fault")
    })
    public Provider getProviderFromNotice(
        @WebParam(name = "docId", partName = "docId")
        long docId)
        throws Fault
    ;

}
